import { Component, OnInit } from '@angular/core'
import { Table } from 'primeng/table'

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrl: './table.component.css',
})
export class TableComponent implements OnInit {
  customers!: any[]

  representatives!: any[]

  loading: boolean = false
  value: string | undefined
  isChecked: boolean = false

  ngOnInit() {
    this.customers = [
      {
        id: 1000,
        name: 'Person 1',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 1',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
        balance: 70663,
      },
      {
        id: 1001,
        name: 'Person 2',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 2',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Anna Fali', image: 'annafali.png' },
        balance: 71663,
      },
      {
        id: 1002,
        name: 'Person 3',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 3',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
        balance: 72663,
      },
      {
        id: 1003,
        name: 'Person 4',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 4',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
        balance: 73663,
      },
      {
        id: 1004,
        name: 'Person 5',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 5',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Elwin Sharvill', image: 'elwinsharvill.png' },
        balance: 74663,
      },
      {
        id: 1005,
        name: 'Person 6',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 6',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
        balance: 75663,
      },
      {
        id: 1006,
        name: 'Person 7',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 7',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Ivan Magalhaes', image: 'ivanmagalhaes.png' },
        balance: 76663,
      },
      {
        id: 1007,
        name: 'Person 8',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 8',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Onyama Limba', image: 'onyamalimba.png' },
        balance: 77663,
      },
      {
        id: 1008,
        name: 'Person 9',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 9',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Stephen Shaw', image: 'stephenshaw.png' },
        balance: 78663,
      },
      {
        id: 1009,
        name: 'Person 10',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 10',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
        balance: 79663,
      },
      {
        id: 1010,
        name: 'Person 11',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 11',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
        balance: 80663,
      },
      {
        id: 1011,
        name: 'Person 12',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 12',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Anna Fali', image: 'annafali.png' },
        balance: 81663,
      },
      {
        id: 1012,
        name: 'Person 13',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 13',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
        balance: 82663,
      },
      {
        id: 1013,
        name: 'Person 14',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 14',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
        balance: 83663,
      },
      {
        id: 1014,
        name: 'Person 15',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 15',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Elwin Sharvill', image: 'elwinsharvill.png' },
        balance: 84663,
      },
      {
        id: 1015,
        name: 'Person 16',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 16',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
        balance: 85663,
      },
      {
        id: 1016,
        name: 'Person 17',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 17',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Ivan Magalhaes', image: 'ivanmagalhaes.png' },
        balance: 86663,
      },
      {
        id: 1017,
        name: 'Person 18',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 18',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Onyama Limba', image: 'onyamalimba.png' },
        balance: 87663,
      },
      {
        id: 1018,
        name: 'Person 19',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 19',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Stephen Shaw', image: 'stephenshaw.png' },
        balance: 88663,
      },
      {
        id: 1019,
        name: 'Person 20',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 20',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
        balance: 89663,
      },
      {
        id: 1020,
        name: 'Person 21',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Company 21',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
        balance: 90663,
      },
    ]

    this.customers.forEach((customer) => (customer.date = new Date(<Date>customer.date)))

    this.representatives = [
      { name: 'Amy Elsner', image: 'amyelsner.png' },
      { name: 'Anna Fali', image: 'annafali.png' },
      { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
      { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
      { name: 'Elwin Sharvill', image: 'elwinsharvill.png' },
      { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
      { name: 'Ivan Magalhaes', image: 'ivanmagalhaes.png' },
      { name: 'Onyama Limba', image: 'onyamalimba.png' },
      { name: 'Stephen Shaw', image: 'stephenshaw.png' },
      { name: 'Xuxue Feng', image: 'xuxuefeng.png' },
    ]
  }

  clear(table: Table) {
    table.clear()
  }
}
